### ISSUE TITLE
Frontend internacionalization

### ISSUE THREAD

**Issue by Murias10** [Arquisoft/wiq_en3b#108]
We are going to add in settings the option to change the frontend language, this part is only for the frontend (the management of the language of the questions and answers will be elaborated in another section)

**Comment by Murias10** [comment]
![image](https://github.com/Arquisoft/wiq_en3b/assets/124095477/528b5d3b-14fa-4d42-a3f6-fda30114d456)
Possible languages to select

**Comment by didierrc** [comment]
Just to noted here, i18n for QS has been done at #101
