### ISSUE TITLE
Move the option to change language and volume slider to the header

### ISSUE THREAD

**Issue by Raulms29** [Arquisoft/wiq_en3b#143]

**Comment by Veneiro** [comment]
# Volume Slider
![Untitled_Project_V3](https://github.com/Arquisoft/wiq_en3b/assets/50624734/05c4ddd0-462b-4a33-b645-8fbaeb78a873)

# Language Selector
![Recorded_screen_1_V1](https://github.com/Arquisoft/wiq_en3b/assets/50624734/f4c485c9-5455-45c0-8736-8aec61e96dd5)
