### ISSUE TITLE
Add animal animations to our page

### ISSUE THREAD

**Issue by didierrc** [Arquisoft/wiq_en3b#149]

**Comment by krovostcora** [comment]
Currently, it looks like in the attached video

I also plan to create a 'Hello-cat' for the registration page, which will greet new users, as well as different cats for Quiz results

Additionally, I plan to add other animals

https://github.com/Arquisoft/wiq_en3b/assets/58918909/5f362a52-13f4-49f7-9fa8-07aaa49824c8

**Comment by didierrc** [comment]
Wow! That's really cool. I've been thinking in changing the name of our Application to something related to animals and questions to have the vibe of what you will add 🦁 If you come with any idea share it and we can think of making a soft redesign of the App in the next meeting.

**Comment by krovostcora** [comment]
Thanks a lot for positive feedback!)

I've come up with some ideas for Application name :

- Wild Wits
- Paws & Questions
- _PawQuest_
- _PawQuiz_
- Furry Facts (not sure about this one bcs most of added animals don't have fur)

and I'll continue brainstorming for more ideas! ^^
