### ISSUE TITLE
Doc06

### ISSUE THREAD

**Issue by carlosmndzg** [Arquisoft/wiq_en3b#17]
Do the part 6 of the Project Documentation: "Runtime View"

**Comment by Raulms29** [comment]
There seems to be a folder .vscode which contains an empty .json file. We should remove it on a future commit, since it shouldn't be there.

**Comment by carlosmndzg** [comment]
There is a mistake in the part "Login scenario" in both description and diagram. In the part  "Backend->Database: Verifies user credentials | Database-->Backend: Responds with verification status" it is not the database the one that performs the verification. 

The procedure should be the following:

1.  The backend receives both credentials (username and password), where the password is as plain text.
2.  Backend asks the Database for the password of the username provided (this password is encrypted)
3.  When the backend receives the password (encrypted) from the database, the backend encrypts the password (as plain text)
4.  Then, a comparison between the one from the database and the encrypted by the backend is made. If they match, login successful, otherwise incorrect credentials.

**Comment by didierrc** [comment]
I just have a small complaint, didn't we talk about Backend just returning JSONs?? But seems that in diagram backend responds with a view
