### ISSUE TITLE
Create Base Application Code

### ISSUE THREAD

**Issue by Raulms29** [Arquisoft/wiq_en3b#33]

**Comment by Raulms29** [comment]
I just created the skeleton of the History Service, and I found quite a few things to consider when doing it, specially with Dockerfiles. I could make a .md file explaining more or less how to do it or, if you prefer, we can talk about it in tomorrow's meeting.

**Comment by Raulms29** [comment]
If you have time, could you take a look at the model I created on history-model.ts?
I am not very familiar with MongoDB and Mongoose, so I would appreciate a second opinion.

**Comment by carlosmndzg** [comment]
I looked at the History Model and from an implementation point of view the code seems good except that when you created a new document, if you pass to it only the username and password, the History document is not created. To avoid this, two approaches are possible.

## First approach. 
Passing it in the request body, this performed by the frontend, so in the service nothing should be changed.
## Second approach. 
Creating it automatically when it is not passed. For that, in the UserSchema is just changing from:

```js
history: historySchema
```

to the following:

```js
history: {
    type: historySchema,
    default: {}
  }
```

# Something more
However, I have some questions. I think that in the meetings we said that the UsersService and HistoryService are the same, but you implemented a new microservice. In fact, it does not look bad, but in case that we are making a new microservice, we should take some considerations regarding the database (the previous schema). 
Do we want the HistoryService database to be different from the Userservice database or not?

1. If that is the case, we would have replicated data like the user credentials ("password and createdAt"), where we could just store the username to know who owns the statistics.
2. If it is not the case, and we share the database, the schema seems good, but we should share the same model between the UserService and HistoryService.

We can talk about all of this in the following meeting.
