### ISSUE TITLE
Fix Try Again button

### ISSUE THREAD

**Issue by didierrc** [Arquisoft/wiq_en3b#70]
The button of Try Again does not correctly develop its functionality. It must generate new questions, not show the same ones.

**Comment by Murias10** [comment]
![image](https://github.com/Arquisoft/wiq_en3b/assets/124095477/348279b8-733c-49ff-a027-ac98bd9064ba)
Now instead of being called the try again button, it is called play again, when you click on it you start a game with new questions.
