### ISSUE TITLE
Errors returning always 400

### ISSUE THREAD

**Issue by didierrc** [Arquisoft/wiq_en3b#86]
While I was doing the implementation of the OpenAPI I noticed how some code for authenticationService or userService
are always returning error code 400 (client error) even when a Server error could happen, for example, retrieving
data from Database. I link a photo to illustrate this:

![Screenshot 2024-03-25 202504](https://github.com/Arquisoft/wiq_en3b/assets/109146445/c8d0fb7c-7d2c-42a7-a7f6-ee7ba113fe74)

```
try{
  ...
  ...
  // May throw a MongoDB exception for any reason!
  const leaderboard = await User.find( {} ); // omitted filters for brevity
  ...
  ...
} catch(error){
  res.status(400) // Always returning 400 error code
}

```

Please, check along the code for these things!

**Comment by IyanRobles** [comment]
I'll take a look into the code, thanks for noticing!

**Comment by didierrc** [comment]
TryCatches to handle 500 errors added by @IyanRobles in #87. Closing this issue
